<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>FutabaCLI.Igarashi</StartupObject>
    <AssemblyName>futaba</AssemblyName>
    <ApplicationIcon>..\futaba.ico</ApplicationIcon>
    <IsAotCompatible>true</IsAotCompatible>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Configurations>Debug;Release;UnitTests</Configurations>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Title>futaba</Title>
    <Authors>kan</Authors>
    <Copyright>(c) 2026</Copyright>
    <PackageProjectUrl>https://spannerisms.github.io/futaba</PackageProjectUrl>
    <VersionPrefix>0.2.1.0</VersionPrefix>
    <VersionSuffix>beta</VersionSuffix>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/spannerisms/futaba</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='UnitTests|AnyCPU'">
    <DebugType>portable</DebugType>
    <Optimize>False</Optimize>
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Futaba\Futaba.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\futaba.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\logo.png" LogicalName="futaba.png" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='UnitTests'">
    <None Update="Tests\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>